### ISSUE TITLE
Dark Mode 🌚

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulibWorkflows#7]
Please add darkmode (https://github.com/Clashsoft/bootstrap-darkmode) to the generated pages.

Also, the dark mode should be synced with the selected theme on fulib.org

**Comment by Kuenssi** [comment]
- [x] Add `    <link rel="stylesheet" href="https://unpkg.com/bootstrap-darkmode@5.0.0-beta.1/css/darktheme.css"/>` to <head>
- [x] Add `data-theme="auto"` do `<body>`
- [x] Stylize inputs
